title: Malujme duší
desctiption: Karna is a responsive jekyll theme which includes pinterest like pins.
url: http://www.malujmedusi.cz
permalink: ':title/'

markdown: kramdown

sass:
  style: compressed

highlight: rouge

include: 
  - _pages
